version: '3.0'
networks:
  skeleton:
    driver: bridge

services:
  php:
    container_name: 'php'
    networks:
      - skeleton
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - './../:/var/www'
    environment:
    #  PHP_IDE_CONFIG: "serverName=paybis"
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www'
    extra_hosts:
    # for step debugging with Xdebug
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: 'nginx'
    image: nginx:1.23.2-alpine
    networks:
      - skeleton
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - '..:/var/www:rw'
      - '../docker/nginx/default.nginx:/etc/nginx/default.conf'

  postgres:
    container_name: 'pg-skeleton'
    image: postgres:15.1-alpine
    networks:
      - skeleton
    ports:
      - '5433:5432'
    working_dir: /app
    restart: always
    environment:
      -POSTGRES_DB: 'POSTGRES_PB'
      -POSTGRES_USER: 'paybis'
      -POSTGRES_PASSWORD: 'paybis'
    volumes:
      - ../db/dump:/app/dump
      - ../db/postgresql:/var/lib/postgresql/data:rw
